//! Provider catalog data for the new-account wizard's provider picker
//! (S4): the static default `PROVIDER_OPTIONS` table (208 entries), the
//! `ProviderInfo` snapshot type, and the alphabetical `sort_providers`
//! applied wherever a provider list enters `App`.

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ProviderInfo {
    pub(crate) slug: String,
    pub(crate) display_name: String,
}

/// Sort a provider list for the new-account wizard's picker (step 1):
/// alphabetical by display name. The picker shows display names only (the
/// canonical slug is deliberately hidden — it is easily confused with the
/// account slug entered in step 2), so display-name order is what the user
/// perceives. Case-insensitive so mixed-case names ("abliteration.ai",
/// "Alibaba Coding Plan", "NEAR AI Cloud") sit next to their letter peers
/// instead of being split by ASCII case. Applied wherever a provider list
/// enters `App` (the static `PROVIDER_OPTIONS` default and every daemon
/// `CatalogUpdated`), because the catalog itself is deliberately ordered by
/// provenance, not alphabetically.
pub(crate) fn sort_providers(providers: &mut [ProviderInfo]) {
    // `sort_by_cached_key` lowercases each display name once (O(n) allocations)
    // instead of per comparison (O(n log n)).  The list is re-sorted at
    // `App::new` and on every `CatalogUpdated`, so the one-time key cache is
    // the cheaper path at both call sites.  Stable, like `sort_by`.
    providers.sort_by_cached_key(|p| p.display_name.to_lowercase());
}

/// The static default provider picker list for the new-account wizard
/// (phase 1) — 208 entries.
///
/// Generated from the merged catalog (models.dev base + bundled overlay) by
/// `cargo run --bin catalog-gen` — regenerate and paste the printed list when
/// the catalog changes. Entry order simply mirrors the catalog's provenance
/// order (models.dev snapshot order, then overlay-only providers) — it is not
/// what the user sees: `App` sorts the list alphabetically when it builds the
/// picker (`sort_providers`).
///
/// This is the DEFAULT/fallback: `App.providers` starts from it and is
/// replaced wholesale whenever the daemon broadcasts `CatalogUpdated` (S4),
/// so the picker tracks the daemon's live catalog (cache + user overlay)
/// rather than this compile-time snapshot.
pub(crate) const PROVIDER_OPTIONS: &[(&str, &str)] = &[
    ("zhipuai", "Zhipu AI"),
    ("lucidquery", "LucidQuery"),
    ("anyapi", "AnyAPI"),
    ("impossibl", "Impossibl"),
    ("blueclaw", "Blue Claw"),
    ("tencent-tokenhub", "Tencent TokenHub"),
    ("fireworks-ai", "Fireworks AI"),
    ("greenpt", "GreenPT"),
    ("wandb", "Weights & Biases"),
    ("crossmodel", "CrossModel"),
    ("llmtr", "LLMTR"),
    ("claudinio", "Claudinio"),
    ("coralbricks", "CoralBricks"),
    ("snowflake-cortex", "Snowflake Cortex"),
    ("cohere", "Cohere"),
    ("opencode-go", "OpenCode Go"),
    ("poe", "Poe"),
    ("baseten", "Baseten"),
    ("nvidia", "Nvidia"),
    ("nebius", "Nebius Token Factory"),
    ("vivgrid", "Vivgrid"),
    ("google", "Google"),
    ("thinkingmachines", "Thinking Machines"),
    ("lilac", "Lilac"),
    ("stepfun-ai-step-plan", "StepFun Step Plan (Global)"),
    ("zhipuai-coding-plan", "Zhipu AI Coding Plan"),
    ("nano-gpt", "NanoGPT"),
    ("fastrouter", "FastRouter"),
    ("nearai", "NEAR AI Cloud"),
    ("daoxe", "DaoXE"),
    ("crof", "CrofAI"),
    ("qvac", "QVAC"),
    ("abliteration-ai", "abliteration.ai"),
    ("alibaba-coding-plan-cn", "Alibaba Coding Plan (China)"),
    ("llmgateway", "LLM Gateway"),
    ("kenari", "Kenari"),
    ("friendli", "Friendli"),
    ("opencode", "OpenCode Zen"),
    ("sakana", "Sakana AI"),
    ("trustedrouter", "TrustedRouter"),
    ("salad-cloud", "SaladCloud AI Gateway"),
    ("atomic-chat", "Atomic Chat"),
    ("inception", "Inception"),
    ("stepfun-step-plan", "StepFun Step Plan (China)"),
    ("cloudflare-workers-ai", "Cloudflare Workers AI"),
    ("modelscope", "ModelScope"),
    ("github-copilot", "GitHub Copilot"),
    ("302ai", "302.AI"),
    ("helicone", "Helicone"),
    ("alibaba-coding-plan", "Alibaba Coding Plan"),
    ("watsonx", "watsonx.ai"),
    ("submodel", "submodel"),
    ("neon", "Neon"),
    ("infomaniak", "Infomaniak"),
    ("ambient", "Ambient"),
    ("dinference", "DInference"),
    ("privatemode-ai", "Privatemode AI"),
    ("unorouter", "UnoRouter"),
    ("frogbot", "FrogBot"),
    ("the-grid-ai", "The Grid AI"),
    ("sap-ai-core", "SAP AI Core"),
    ("upstage", "Upstage"),
    ("cline-pass", "ClinePass"),
    ("regolo-ai", "Regolo AI"),
    ("aiand", "ai&"),
    ("pioneer", "Pioneer"),
    ("siliconflow", "SiliconFlow"),
    ("ai-router", "AI-ROUTER"),
    ("zenmux", "ZenMux"),
    ("inference", "Inference"),
    ("evroc", "evroc"),
    ("abacus", "Abacus"),
    ("edenai", "Eden AI"),
    ("inceptron", "Inceptron"),
    ("empiriolabs", "EmpirioLabs AI"),
    ("alibaba-token-plan", "Alibaba Token Plan"),
    ("meta", "Meta"),
    ("azure-cognitive-services", "Azure Cognitive Services"),
    ("wafer.ai", "Wafer"),
    ("clarifai", "Clarifai"),
    ("iflowcn", "iFlow"),
    ("gitlab", "GitLab Duo"),
    ("bailing", "Bailing"),
    ("venice", "Venice AI"),
    ("mixlayer", "Mixlayer"),
    ("scaleway", "Scaleway"),
    ("togetherai", "Together AI"),
    ("digitalocean", "DigitalOcean"),
    ("moonshotai-cn", "Moonshot AI (China)"),
    ("model-oracle-ai", "Model Oracle AI"),
    ("drun", "D.Run (China)"),
    ("lmstudio", "LMStudio"),
    ("ovhcloud", "OVHcloud AI Endpoints"),
    ("zeldoc", "Zeldoc"),
    ("auriko", "Auriko"),
    ("azure", "Azure"),
    ("kuae-cloud-coding-plan", "KUAE Cloud Coding Plan"),
    ("modal", "Modal"),
    ("qihang-ai", "QiHang"),
    ("berget", "Berget.AI"),
    ("google-vertex-anthropic", "Vertex (Anthropic)"),
    ("moark", "Moark"),
    ("nova", "Nova"),
    ("vultr", "Vultr"),
    ("io-net", "IO.NET"),
    ("neuralwatt", "Neuralwatt"),
    ("aki-io", "AKI.IO"),
    ("xai", "xAI"),
    ("hetzner", "Hetzner"),
    ("zenifra", "Zenifra"),
    ("aihubmix", "AIHubMix"),
    ("morph", "Morph"),
    ("umans-ai-coding-plan", "Umans AI Coding Plan"),
    ("mistral", "Mistral"),
    ("umans-ai", "Umans AI"),
    ("ofox", "Ofox"),
    ("orcarouter", "OrcaRouter"),
    ("xiaomi-token-plan-cn", "Xiaomi Token Plan (China)"),
    ("v0", "v0"),
    ("poolside", "Poolside"),
    ("routing-run", "routing.run"),
    ("google-vertex", "Vertex"),
    ("tencent-token-plan", "Tencent Token Plan"),
    ("synthetic", "Synthetic"),
    ("zai-coding-plan", "Z.AI Coding Plan"),
    ("gmicloud", "GMI Cloud"),
    ("freemodel", "FreeModel"),
    ("amazon-bedrock", "Amazon Bedrock"),
    ("xiaomi-token-plan-ams", "Xiaomi Token Plan (Europe)"),
    ("minimax", "MiniMax (minimax.io)"),
    ("groq", "Groq"),
    ("deepseek", "DeepSeek"),
    ("kimi-for-coding", "Kimi For Coding"),
    ("requesty", "Requesty"),
    ("tensorx", "TensorX"),
    ("llama", "Llama"),
    ("kilo", "Kilo Gateway"),
    ("merge-gateway", "Merge Gateway"),
    ("scx", "SCX.ai"),
    ("cloudferro-sherlock", "CloudFerro Sherlock"),
    ("modelis", "Modelis"),
    ("subconscious", "Subconscious"),
    ("tencent-coding-plan", "Tencent Coding Plan (China)"),
    ("hyper", "Charm Hyper"),
    ("alibaba", "Alibaba"),
    ("vercel", "Vercel AI Gateway"),
    ("alibaba-cn", "Alibaba (China)"),
    ("novita-ai", "NovitaAI"),
    ("openrouter", "OpenRouter"),
    ("huggingface", "Hugging Face"),
    ("minimax-coding-plan", "MiniMax Token Plan (minimax.io)"),
    ("siliconflow-cn", "SiliconFlow (China)"),
    ("tinfoil", "Tinfoil"),
    ("xiaomi", "Xiaomi"),
    ("stackit", "STACKIT"),
    ("deepinfra", "Deep Infra"),
    ("anthropic", "Anthropic"),
    ("cloudflare-ai-gateway", "Cloudflare AI Gateway"),
    ("lynkr", "Lynkr"),
    ("alibaba-token-plan-cn", "Alibaba Token Plan (China)"),
    ("stepfun-ai", "StepFun (Global)"),
    ("chutes", "Chutes"),
    ("cerebras", "Cerebras"),
    ("qiniu-ai", "Qiniu"),
    ("longcat", "LongCat"),
    ("ollama-cloud", "Ollama Cloud"),
    ("jiekou", "Jiekou.AI"),
    ("perplexity", "Perplexity"),
    ("perplexity-agent", "Perplexity Agent"),
    ("moonshotai", "Moonshot AI"),
    ("openai", "OpenAI"),
    ("xpersona", "Xpersona"),
    ("sarvam", "Sarvam AI"),
    ("zai", "Z.AI"),
    ("inferx", "InferX"),
    ("meganova", "Meganova"),
    ("stepfun", "StepFun (China)"),
    ("cortecs", "Cortecs"),
    ("xiaomi-token-plan-sgp", "Xiaomi Token Plan (Singapore)"),
    ("hpc-ai", "HPC-AI"),
    ("minimax-cn", "MiniMax (minimaxi.com)"),
    ("ebcloud", "EBCloud"),
    ("databricks", "Databricks"),
    (
        "minimax-cn-coding-plan",
        "MiniMax Token Plan (minimaxi.com)",
    ),
    ("aimlapi", "aimlapi.com"),
    ("ant-ling", "Ant Ling"),
    ("arcee", "Arcee AI"),
    ("atlascloud", "Atlas Cloud"),
    ("bankr", "Bankr"),
    ("custom-anthropic", "Custom Anthropic-Compatible"),
    ("custom-openai", "Custom OpenAI-Compatible"),
    ("futurmix", "FuturMix"),
    ("gitlawb-opengateway", "GitLawb OpenGateway"),
    ("iflytek", "iFlytek Spark"),
    ("iflytek-astron", "iFlytek Astron MaaS"),
    ("kimi-code", "Kimi Code subscription"),
    ("llama-swap", "Llama Swap"),
    ("nous", "Nous Research"),
    ("ollama", "Ollama (Local)"),
    ("omlx", "oMLX"),
    ("openai-codex", "OpenAI Codex subscription"),
    ("openai_compatible", "OpenAI Compatible"),
    (
        "opencode-go-anthropic-compatible",
        "OpenCode Go Anthropic-compatible",
    ),
    ("qwen-token-plan", "Qwen Token Plan"),
    ("qwen-token-plan-cn", "Qwen Token Plan CN"),
    ("routstr", "Routstr"),
    ("tanzu", "VMware Tanzu Platform"),
    ("tensorix", "Tensorix"),
];
