[workspace]
members = [
    "tai-client-core",
    "tai-daemon",
    "tai-keystore",
    "tai-proto",
    "tai-tui",
    "tai-dioxus",
    "tai-im",
]
resolver = "3"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
tai-client-core = { path = "tai-client-core" }
tai-keystore = { path = "tai-keystore" }
tai-proto = { path = "tai-proto" }
tai-im = { path = "tai-im" }
ammonia = "4"
base64 = "0.22"
dirs = "6"
redb = "4"
image = "0.25"
rand = "0.10"
resvg = "0.47"
serde_json = "1"
tokio = { version = "1" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
