[package]
name = "choreo-client-core"
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]

choreo-proto.workspace = true
choreo-sanitize.workspace = true
choreo-transport.workspace = true
choreo-keystore.workspace = true
postcard.workspace = true
thiserror.workspace = true
tracing.workspace = true
uds_windows.workspace = true

[dev-dependencies]
tempfile.workspace = true
