[package]
name = "choreo-markdown"
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
pulldown-cmark = "0.13"
ammonia.workspace = true
thiserror.workspace = true
