[package]
name = "tai-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
base64.workspace = true
dirs.workspace = true
fff-search = "0.9"
hex = "0.4"

gix = { version = "0.85", features = ["tree-editor"] }
hmac = "0.13"
image.workspace = true
rand.workspace = true
redb.workspace = true
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls", "stream", "blocking"] }
resvg.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
sha1 = "0.11"
sha2 = "0.11"
url = "2"
tai-keystore.workspace = true
tai-proto.workspace = true
signal-hook = "0.3"
toml = "1.1"
tracing.workspace = true
tracing-subscriber.workspace = true
ckb-vm = { version = "0.24.14", features = ["asm", "detect-asm"] }

[dev-dependencies]
filetime = "0.2"
tempfile = "3"
