#!/bin/bash
# Shared by scripts/build-ios.sh and scripts/check-ios.sh: generates the cc /
# cxx shims that route C compiles through `zig cc` on non-Mac hosts.
#
# WHY A LIB: the two scripts previously carried byte-identical ~45-line
# heredoc generators for these shims (see build-ios.sh's step-2 comment for
# the full triple-translation rationale: Apple-iOS compiles AND dylib links
# rewrite to zig's aarch64-macos, host builds map to zig's linux-gnu — the
# whole path is COMPILE-VALIDATION only). They diverged once already; this
# keeps them from drifting again. The rustc shim is target-script-specific
# (different arg handling) and stays in each caller.
#
# Usage: write_ios_cc_shims <shim_dir> <generator_script_name>
#   <generator_script_name> is stamped into the generated files' comment
#   header ("Generated by scripts/<name> — do not edit.") so a stale shim in
#   target/ios-shims/ shows where its current generator lives.
write_ios_cc_shims() {
    local shim_dir="$1"
    local generator="$2"

    for name in cc cxx; do
        # Expand the zig subcommand AT GENERATION TIME (unescaped below — the
        # original heredocs did the same, emitting a hardcoded `zig cc` / `zig
        # c++` per shim). The runtime text must not reference $name: the
        # generated script has no such variable.
        local backend=cc
        [ "$name" = cxx ] && backend=c++
        cat > "$shim_dir/$name" <<EOF
#!/bin/bash
# Generated by scripts/$generator — do not edit (full rationale in
# scripts/build-ios.sh, step 2: the cc-wrapper comment).
# Translate clang/rust-style target triples to zig's form instead of
# stripping them: some build scripts (e.g. pdf-inspector) both COMPILE for
# the Apple target and LINK a dylib for it, so the -target must survive.
# ALL Apple-iOS invocations — compiles AND the dylib links — keep the macOS
# rewrite (aarch64-macos): zig ships darwin libc headers and the macOS
# stub dylibs (libSystem/iconv/framework tbds) only for macOS, so an iOS
# target cannot link here. This whole shim path is COMPILE-VALIDATION only
# (the final Apple link happens on the Mac with the native toolchain — the
# shim is never exported when xcrun is present), so a macOS-flavored link
# is exactly the right fidelity: it proves the C code links.
# Default (no target seen): zig's linux-gnu host target.
zig_target=x86_64-linux-gnu
skip=0
args=()
for a in "\$@"; do
  if [ "\$skip" = 1 ]; then
    skip=0
    t="\$(printf '%s' "\$a" | sed -e 's/^arm64-/aarch64-/' -e 's/-unknown-/-/' \
        -e 's/^aarch64-apple-ios\([0-9.]*\)\$/aarch64-ios/')"
    case "\$t" in aarch64-ios*) t=aarch64-macos ;; esac
    zig_target="\$t"
    args+=(-target "\$t")
    continue
  fi
  case "\$a" in
    -target)
      skip=1 ;;
    --target=*)
      t="\$(printf '%s' "\${a#--target=}" | sed -e 's/^arm64-/aarch64-/' -e 's/-unknown-/-/' \
          -e 's/^aarch64-apple-ios\([0-9.]*\)\$/aarch64-ios/')"
      case "\$t" in aarch64-ios*) t=aarch64-macos ;; esac
      zig_target="\$t"
      args+=(-target "\$t") ;;
    -miphoneos-version-min*)
      # clang-only deployment-target flag; zig derives it from -target.
      ;;
    *)
      args+=("\$a") ;;
  esac
done
EOF
    # The exec line is appended with printf rather than the heredoc: the
    # runtime text must be "${args[@]+"${args[@]}"}" — plain quotes so each
    # array element stays its own word, with the $ still unexpanded in the
    # generated file. Inside an unquoted heredoc you cannot have BOTH a plain
    # quote and a deferred ${...} (an escaped prefix survives as a literal
    # backslash before the quote — verified empirically against the shim the
    # old heredocs produced); printf's format string has no such interaction.
    printf 'exec zig %s -target "$zig_target" "${args[@]+"${args[@]}"}"\n' \
        "$backend" >> "$shim_dir/$name"
    done
    chmod +x "$shim_dir/cc" "$shim_dir/cxx"
}
