//! Loads the embedded catalog: a postcard-serialized, normalized models.dev
//! base (`catalog.bin`) merged with the bundled `models-overlay.toml` policy
//! layer.
//!
//! The artifact pipeline mirrors the data flow:
//!
//! ```text
//! catalog/models.dev.json (local, gitignored) ──(catalog-gen: normalize_modelsdev)──► catalog/catalog.bin (committed)
//!                                                                      │
//!                                             include_bytes! (this file)▼
//!                                    load_bundled_base() ──► ProviderEntry base
//!                                             │
//!                     catalog/models-overlay.toml (include_str!) │
//!                                             ▼
//!                              merge_overlay() ──► load_catalog()
//! ```
//!
//! `catalog/models.dev.json` is a **local artifact**: `catalog-gen` fetches a
//! fresh snapshot from models.dev when it is missing and caches it there
//! (gitignored), so `catalog.bin` is the only committed catalog data file.
//!
//! The overlay is merged at load time and never baked into `catalog.bin`, so
//! S4 can re-merge the same base with a user overlay at runtime without
//! re-downloading anything.

use super::{ProviderEntry, merge_overlay};

/// The bundled overlay TOML source (`include_str!`). Exposed as a function
/// (not just folded into `load_catalog`) because S4's runtime refresh
/// re-merges the *current* base with the bundled layer plus a user overlay
/// on every catalog swap — the daemon needs the source to re-apply it, it
/// cannot reuse the merged result.
pub fn bundled_overlay_src() -> &'static str {
    include_str!("../../catalog/models-overlay.toml")
}

/// The bundled catalog: the normalized models.dev base overlaid with the
/// checked-in `models-overlay.toml` policy layer. This is what
/// `PROVIDER_CATALOG` is initialized from (and what the swap tests restore).
pub(crate) fn load_catalog() -> Vec<ProviderEntry> {
    merge_overlay(
        &load_bundled_base(),
        include_str!("../../catalog/models-overlay.toml"),
    )
}

/// Deserialize the embedded `catalog.bin` (postcard of the NORMALIZED
/// models.dev base, generated by `cargo run --bin catalog-gen`).
///
/// A failed deserialization of embedded data means the shipped binary is
/// corrupt (wrong catalog.bin for this code version) — log it as an error and
/// return an empty catalog rather than crashing the daemon. The
/// `embedded_catalog_loads` unit test catches a real mismatch at build time.
pub fn load_bundled_base() -> Vec<ProviderEntry> {
    let bytes = include_bytes!("../../catalog/catalog.bin");
    match postcard::from_bytes(bytes) {
        Ok(base) => base,
        Err(e) => {
            tracing::error!(
                error = %e,
                bytes = bytes.len(),
                "embedded catalog.bin failed to deserialize; catalog is empty",
            );
            Vec::new()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_base_is_non_empty_and_ordered() {
        let base = load_bundled_base();
        assert!(
            base.len() >= 150,
            "expected >=150 providers from the models.dev base, got {}",
            base.len()
        );
        // The base must be provider-ordered deterministically; every provider
        // carries its slug and a derived default model.
        for entry in &base {
            assert!(!entry.slug.is_empty(), "empty slug in base");
            assert!(
                !entry.default_model.is_empty(),
                "empty default model for {}",
                entry.slug
            );
        }
    }

    #[test]
    fn embedded_blob_matches_local_snapshot() {
        use crate::catalog::normalize_modelsdev;

        // The committed `catalog.bin` must equal postcard(normalize(snapshot)).
        // The snapshot (`catalog/models.dev.json`) is gitignored and absent in
        // CI, so this test early-returns when it is missing — it guards
        // developers who have the snapshot locally. The CI-appropriate guard
        // is `cargo run --bin catalog-gen -- --check`, which rebuilds the
        // comparison from a fresh fetch (or the local snapshot) without
        // writing anything. This test deliberately does NOT touch the
        // `PROVIDER_CATALOG` global, so it must not be serialized.
        let snapshot_path = concat!(env!("CARGO_MANIFEST_DIR"), "/catalog/models.dev.json");
        let Ok(snapshot) = std::fs::read_to_string(snapshot_path) else {
            return;
        };
        let expected = postcard::to_allocvec(&normalize_modelsdev(&snapshot))
            .expect("postcard serialization of the normalized snapshot succeeds");
        assert_eq!(
            expected,
            include_bytes!("../../catalog/catalog.bin"),
            "catalog.bin is stale: run `cargo run --bin catalog-gen`",
        );
    }
}
