[package]
name = "tai-im"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
tai-proto.workspace = true
tai-keystore.workspace = true
tai-client-core.workspace = true
tai-markdown.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
ureq.workspace = true
serde.workspace = true
serde_json.workspace = true
ammonia.workspace = true
