[package]
name = "tai-im"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
tai-proto.workspace = true
tai-keystore.workspace = true
tai-client-core.workspace = true
bincode.workspace = true
tai-markdown.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
frankenstein = { version = "0.50", features = ["client-ureq"] }
ammonia.workspace = true
tempfile = "3"
