#!/usr/bin/env bash
# build-ios.sh — compiles choreo-gui for iOS and stages the artifacts the Xcode
# scaffold (ios/) links against. It runs on ANY host with three behaviors:
#
#   - WITH a Mac/Xcode (xcrun present): full build per target (device + sim),
#     staging the rlib and C static archives for the Xcode project.
#   - WITHOUT Xcode (e.g. the Linux check laptop): the SAME compile stages run
#     via the zig shim set (zig cc provides C compilation; rustc provides all
#     Rust codegen), and the final Apple dylib/app link is SKIPPED with a clear
#     notice — everything short of Apple's linker is verified. This mirrors how
#     scripts/build-android.sh documents its own rustflags/toolchain traps, so
#     read those notes there too.
#
# Staging layout (matches ios/project.yml's LIBRARY_SEARCH_PATHS):
#   target/ios/aarch64-apple-ios/<profile>/      libchoreo_gui.rlib + *.a
#   target/ios/aarch64-apple-ios-sim/<profile>/  same, simulator slice
#
# Prerequisites (Mac): rustup targets aarch64-apple-ios[ -sim], Xcode.
# Prerequisites (Linux): same rustup targets, zig >= 0.13 on PATH.
#
# NOTE (the -C target-cpu=native trap): the workspace's profile rustflags and
# ~/.cargo/config.toml [build] rustflags both carry host-only codegen flags.
# Profile rustflags are not suppressible via RUSTFLAGS env (see
# build-android.sh's header), so this script installs a RUSTC wrapper that
# strips `-C target-cpu=native` for Apple targets; on Linux it additionally
# routes cc-rs through `zig cc` with a fake SDKROOT so cc-rs never needs
# xcrun, and rewrites cc-rs's iOS C target to zig's macOS target (zig ships
# macOS darwin libc headers but not iOS ones — compile-only difference; the
# final link happens on the Mac regardless).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PROFILES=() # unused placeholder kept to mirror build-android.sh's structure

log()  { printf '==> %s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# ── Prerequisite checks ──────────────────────────────────────────────────────
command -v cargo >/dev/null || fail "cargo not found"
command -v zig   >/dev/null || fail "zig not found (Linux shim path; install zig)"

for target in aarch64-apple-ios aarch64-apple-ios-sim; do
    if ! rustup target list --installed | grep -qx "$target"; then
        fail "rustup target not installed: $target — run: rustup target add $target"
    fi
done

# Toolchain: the workspace pins nightly (rust-toolchain.toml); cross builds run
# through it as-is — the shims below neutralize the host-only flags.
RUSTC_REAL="$(rustc --print sysroot)/bin/rustc"

# ── Shim setup ───────────────────────────────────────────────────────────────
SHIM_DIR="$REPO_ROOT/target/ios-shims"
mkdir -p "$SHIM_DIR"

# 1. rustc wrapper: strip `-C target-cpu=native` for Apple targets only.
cat > "$SHIM_DIR/rustc" <<EOF
#!/bin/bash
# Generated by scripts/build-ios.sh — do not edit.
real="$RUSTC_REAL"
has_target=0
for a in "\$@"; do case "\$a" in *apple-ios*) has_target=1 ;; esac; done
if [ \$has_target = 0 ]; then exec "\$real" "\$@"; fi
args=()
for a in "\$@"; do
  if [ "\$a" = "target-cpu=native" ]; then
    if [ "\${#args[@]}" -gt 0 ] && [ "\${args[\${#args[@]}-1]}" = "-C" ]; then
      unset 'args[\${#args[@]}-1]'
    fi
    continue
  fi
  args+=("\$a")
done
exec "\$real" "\${args[@]}"
EOF

# 2. cc wrapper: rewrite cc-rs's iOS C target args to zig's macOS target
#    (zig bundles macOS darwin libc headers, not iOS ones — compile-only).
for name in cc cxx; do
    cat > "$SHIM_DIR/$name" <<EOF
#!/bin/bash
# Generated by scripts/build-ios.sh — do not edit.
args=()
for a in "\$@"; do
  case "\$a" in
    --target=arm64-apple-ios|-target|arm64-apple-ios|-miphoneos-version-min*) ;;
    *) args+=("\$a") ;;
  esac
done
exec zig $([ "$name" = cxx ] && echo c++ || echo cc) -target aarch64-macos "\${args[@]}"
EOF
done
chmod +x "$SHIM_DIR/rustc" "$SHIM_DIR/cc" "$SHIM_DIR/cxx"

# Fake SDK root: cc-rs demands an SDKROOT that (a) exists, (b) doesn't look
# like a mismatched-platform SDK; zig cc tolerates -isysroot pointing at it.
FAKE_SDK="$REPO_ROOT/target/ios-fake-sdk"
mkdir -p "$FAKE_SDK/iPhoneOS.platform"

export RUSTC="$SHIM_DIR/rustc" CC="$SHIM_DIR/cc" CXX="$SHIM_DIR/cxx" AR="zig ar"
export SDKROOT="$FAKE_SDK"
unset RUSTFLAGS || true # env RUSTFLAGS would poison cross codegen anyway

# ── Build + stage ────────────────────────────────────────────────────────────
STAGE_ROOT="$REPO_ROOT/target/ios"
build_one() {
    triple="$1"
    # Debug profile here: the script's job on a non-Mac host is compile
    # validation (fast, no dist-profile fat LTO over the whole Blitz tree).
    # A Mac doing a real app build can pass PROFILE=dist (env) to stage the
    # release artifacts instead.
    profile="${PROFILE:-debug}"
    profile_args=(); [ "$profile" != debug ] && profile_args=(--profile "$profile")
    out="target/$triple/$profile"
    log "building choreo-gui (lib) for $triple ($profile)"
    # cargo rustc --crate-type lib (NOT `cargo build --lib`): the crate also
    # declares a `cdylib` target (for the Android .so scaffold), and `--lib`
    # builds ALL lib crate-types — the cdylib requires Apple's linker, which
    # is exactly the step this script must NOT attempt on a non-Mac host.
    # Restricting the crate-type to `lib` (the rlib) makes the build end at
    # codegen, which needs no external linker.
    cargo rustc -p choreo-gui --lib --crate-type lib --target "$triple" "${profile_args[@]}" \
        || fail "build failed for $triple (see output above)"
    stage="$STAGE_ROOT/$triple/$profile"
    mkdir -p "$stage"
    # The rlib: the artifact the Xcode scaffold links (-lchoreo_gui via
    # -L). `cargo rustc` stages it at $out/libchoreo_gui.rlib (single
    # crate-type); keep the deps/ glob fallback for a future `cargo build`.
    rlib="$out/libchoreo_gui.rlib"
    [ -e "$rlib" ] || rlib="$(ls -1 "$out/deps"/libchoreo_gui-*.rlib 2>/dev/null | head -n1 || true)"
    [ -n "$rlib" ] && [ -e "$rlib" ] || fail "no libchoreo_gui rlib produced under $out"
    cp "$rlib" "$stage/libchoreo_gui.rlib"
    # C static archives the rlib depends on (ring, secp256k1) so the Mac link
    # has everything in one directory — cc-rs leaves them in its out/ dirs.
    find "$out/build/ring" "$out/build/secp256k1-sys" -name '*.a' -exec cp {} "$stage/" \; 2>/dev/null || true
    log "staged $stage"
}

# macOS detection: full build possible only when xcrun (⇒ Xcode) is present.
if command -v xcrun >/dev/null 2>&1; then
    log "Xcode detected — full build (device + simulator)"
    build_one aarch64-apple-ios
    build_one aarch64-apple-ios-sim
else
    log "no Xcode on this host — compile-only build (zig shim path)"
    log "the final Apple dylib/app link CANNOT run here; artifacts staged for a Mac"
    build_one aarch64-apple-ios
    log "skipping aarch64-apple-ios-sim (identical codegen; add on the Mac if needed)"
    cat <<'EOF'

WHAT'S NEXT (on a Mac):
  1. rsync the repo (or at least target/ios/) to the Mac
  2. ./scripts/build-ios.sh            # re-runs with xcrun for the sim slice
  3. brew install xcodegen && cd ios && xcodegen generate
  4. open Choreographr.xcodeproj       # phase 0b: verify the event-loop wiring
EOF
fi

log "done"
