[package]
name = "choreo-transport"
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
choreo-proto.workspace = true
thiserror.workspace = true
tracing.workspace = true
snow.workspace = true
dirs.workspace = true
x25519-dalek.workspace = true
rand.workspace = true

[dev-dependencies]
tempfile.workspace = true
serial_test.workspace = true
