name = "opencode_go"
display_name = "OpenCode Go"
kind = "openai"
base_url = "https://opencode.ai/zen/go/v1"
api_key_env = "OPENCODE_API_KEY"

[[models]]
model = "kimi-k2.6"
context_window = 262144
[[models]]
[[models]]
model = "kimi-k2.5"
context_window = 262144
[[models]]
[[models]]
model = "deepseek-v4-flash"
context_window = 1000000
[[models]]
[[models]]
model = "deepseek-v4-pro"
context_window = 1000000
[[models]]
[[models]]
model = "glm-5.1"
context_window = 204800
[[models]]
[[models]]
model = "glm-5"
context_window = 204800
[[models]]
[[models]]
model = "mimo-v2.5-pro"
context_window = 1048576
[[models]]
[[models]]
model = "mimo-v2.5"
context_window = 262144
[[models]]
[[models]]
model = "mimo-v2-pro"
context_window = 1048576
[[models]]
[[models]]
model = "mimo-v2-omni"
context_window = 262144
[[models]]
[[models]]
model = "minimax-m2.7"
context_window = 204800
[[models]]
[[models]]
model = "minimax-m2.5"
context_window = 204800
[[models]]
[[models]]
model = "qwen3.6-plus"
context_window = 262144
[[models]]
[[models]]
model = "qwen3.5-plus"
context_window = 262144
[[models]]
