[package]
name = "choreo-im"
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
choreo-proto.workspace = true
choreo-keystore.workspace = true
choreo-client-core.workspace = true
choreo-markdown.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
ureq.workspace = true
serde.workspace = true
serde_json.workspace = true
ammonia.workspace = true
